# -*- coding: utf-8 -*-
"""Analise se o cliente pode pegar emprestimo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130t5vWDpOKItmTbfXeI0PLFwzLtr_6k8
"""

def pode_aprovar(idade, renda, valor, parcelas):
    # Regra 1: Idade
    if idade <= 18:
        print("Motivo da recusa: Idade não permitida.")
        return False

    # Regra 2: Renda
    if valor > (renda * 15):
        print("Motivo da recusa: Valor do empréstimo excede 15x a renda mensal.")
        return False

    # Regra 3: Valor mínimo e máximo da parcela (considerando o valor inicial)
    # Esta é uma checagem preliminar. A verificação final com juros será feita depois.
    valor_parcela_base = valor / parcelas
    if not (100 <= valor_parcela_base <= 2000):
        print("Motivo da recusa: O valor da parcela base está fora do limite permitido (R$100 a R$2000).")
        return False

    return True

def calcular_juros(valor, parcelas):
    taxa = 0
    if parcelas <= 6:
        taxa = 0.05  # 5%
    elif 7 <= parcelas <= 12:
        taxa = 0.08  # 8%
    else: # 13 a 24 parcelas
        taxa = 0.10  # 10%

    # Juros simples: valor * taxa * número de meses
    juros_totais = valor * taxa * parcelas
    return juros_totais

def calcular_parcela(valor_total, parcelas):
    return valor_total / parcelas


# --- PROGRAMA PRINCIPAL ---

# 1. SOLICITAR DADOS DO CLIENTE
print("--- SISTEMA DE ANÁLISE DE EMPRÉSTIMO ---")
nome_cliente = input("Nome do cliente: ")
idade = int(input("Idade: "))
renda_mensal = float(input("Renda mensal: R$ "))
valor_emprestimo = float(input("Valor desejado do empréstimo: R$ "))
numero_parcelas = int(input("Número de parcelas (3 a 24): "))

# 2. ANALISAR APROVAÇÃO
print("\nAnalisando...")
if pode_aprovar(idade, renda_mensal, valor_emprestimo, numero_parcelas):
    # Se aprovado, continuar com os cálculos
    print("Análise inicial APROVADA!")

    juros_totais = calcular_juros(valor_emprestimo, numero_parcelas)
    valor_total_com_juros = valor_emprestimo + juros_totais
    valor_da_parcela = calcular_parcela(valor_total_com_juros, numero_parcelas)

    # Exibir resultados finais
    print("\n--- RESULTADO DO EMPRÉSTIMO ---")
    print(f"Empréstimo para {nome_cliente} APROVADO!")
    print(f"Valor total com juros: R$ {valor_total_com_juros:.2f}")
    print(f"Valor de cada parcela ({numero_parcelas}x): R$ {valor_da_parcela:.2f}")
    print(f"Juros totais a pagar: R$ {juros_totais:.2f}")
else:
    # Se reprovado, exibir mensagem
    print("\n--- RESULTADO DO EMPRÉSTIMO ---")
    print(f"Empréstimo para {nome_cliente} NEGADO.")