# -*- coding: utf-8 -*-
"""Calcula o salário final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYFX0aqXQF7RGa5-n13yjipoeytxsl0Q
"""

def calcular_valor_horas_extras(salario_base, horas_extras):
    # 1.5% do salário base por hora extra
    valor_por_hora = salario_base * 0.015
    return valor_por_hora * horas_extras

def calcular_desconto_faltas(salario_base, total_faltas):
    # 2% do salário base por falta
    desconto_por_falta = salario_base * 0.02
    return desconto_por_falta * total_faltas

def calcular_valor_bonus(cargo, recebeu_bonus):
    # Verifica se o funcionário recebeu bônus
    if recebeu_bonus.lower() != 's':
        return 0

    # Retorna o bônus correspondente ao cargo
    if cargo == 1: # Gerente
        return 1000.00
    elif cargo == 2: # Analista
        return 500.00
    elif cargo == 3: # Assistente
        return 300.00
    elif cargo == 4: # Estagiário
        return 100.00
    else:
        return 0 # Cargo inválido não recebe bônus


# --- PROGRAMA PRINCIPAL ---

# 1. SOLICITAR DADOS DO FUNCIONÁRIO
print("--- CÁLCULO DE SALÁRIO ---")
nome = input("Nome do funcionário: ")
cargo = int(input("Cargo (1-Gerente, 2-Analista, 3-Assistente, 4-Estagiário): "))
salario_base = float(input("Salário base: R$ "))
horas_extras = float(input("Total de horas extras trabalhadas: "))
faltas = int(input("Total de faltas no mês: "))
recebeu_bonus = input("Recebeu bônus por desempenho (s ou n): ")

# 2. CALCULAR VALORES USANDO AS FUNÇÕES
valor_extras = calcular_valor_horas_extras(salario_base, horas_extras)
valor_bonus = calcular_valor_bonus(cargo, recebeu_bonus)
valor_descontos = calcular_desconto_faltas(salario_base, faltas)

# 3. CALCULAR TOTAIS
salario_bruto = salario_base
total_acrescimos = valor_extras + valor_bonus
salario_final = salario_bruto + total_acrescimos - valor_descontos

# 4. EXIBIR O RESULTADO
print(f"\n--- FOLHA DE PAGAMENTO: {nome} ---")
print(f"Salário Bruto: R$ {salario_bruto:.2f}")
print(f"Total de Acréscimos (Horas Extras + Bônus): R$ {total_acrescimos:.2f}")
print(f"Total de Descontos (Faltas): R$ {valor_descontos:.2f}")
print(f"Salário Final: R$ {salario_final:.2f}")