# -*- coding: utf-8 -*-
"""informações_caminhão

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywsmvthq0MEfq8YEUhCl0X3JXsafQENr
"""

codigo_estado = int(input("Digite o código do estado de origem (1 a 5): "))
peso_toneladas = float(input("Digite o peso da carga do caminhão em toneladas: "))
codigo_carga = int(input("Digite o código da carga (10 a 40): "))

# 2. CALCULAR O PESO DA CARGA EM QUILOS
# 1 tonelada = 1000 quilos
peso_em_quilos = peso_toneladas * 1000

# 3. DETERMINAR O PREÇO POR KG COM BASE NO CÓDIGO DA CARGA
preco_por_kg = 0
if 10 <= codigo_carga <= 20:
    preco_por_kg = 100.00
elif 21 <= codigo_carga <= 30:
    preco_por_kg = 250.00
elif 31 <= codigo_carga <= 40:
    preco_por_kg = 340.00

# 4. CALCULAR O PREÇO TOTAL DA CARGA
preco_da_carga = peso_em_quilos * preco_por_kg

# 5. DETERMINAR A TAXA DE IMPOSTO COM BASE NO ESTADO DE ORIGEM
taxa_imposto = 0
if codigo_estado == 1:
    taxa_imposto = 0.35  # 35%
elif codigo_estado == 2:
    taxa_imposto = 0.25  # 25%
elif codigo_estado == 3:
    taxa_imposto = 0.15  # 15%
elif codigo_estado == 4:
    taxa_imposto = 0.05  # 5%
elif codigo_estado == 5:
    taxa_imposto = 0.00  # Isento

# 6. CALCULAR O VALOR DO IMPOSTO
valor_do_imposto = preco_da_carga * taxa_imposto

# 7. CALCULAR O VALOR TOTAL (CARGA + IMPOSTOS)
valor_total_transportado = preco_da_carga + valor_do_imposto

# 8. EXIBIR OS RESULTADOS
print("\n--- RESUMO DO CÁLCULO ---")
print(f"Peso da carga em quilos: {peso_em_quilos:.2f} kg")
print(f"Preço da carga: R$ {preco_da_carga:.2f}")
print(f"Valor do imposto: R$ {valor_do_imposto:.2f}")
print(f"Valor total transportado (Carga + Impostos): R$ {valor_total_transportado:.2f}")