# -*- coding: utf-8 -*-
"""lados de um triângulo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZte8uX9X4BMavg-CgjhCdx_h6424Kzd
"""

# Usamos map() para aplicar a função float a cada item da lista gerada pelo split()
l1, l2, l3 = map(float, input("Digite os três lados do triângulo, separados por espaço: ").split())

# 2. ORDENAR OS LADOS EM ORDEM DECRESCENTE
lados = sorted([l1, l2, l3], reverse=True)
a, b, c = lados[0], lados[1], lados[2]

# Primeira condição: verificar se forma um triângulo
if a >= (b + c):
    print("NAO FORMA TRIANGULO")
else:
    # Se forma um triângulo, verificamos os outros casos.
    # Verificação do tipo de ângulo
    if a**2 == b**2 + c**2:
        print("TRIANGULO RETANGULO")
    elif a**2 > b**2 + c**2:
        print("TRIANGULO OBSTUSANGULO")
    elif a**2 < b**2 + c**2:
        print("TRIANGULO ACUTANGULO")

    # Verificação quanto aos lados (pode ser executada em conjunto com a de cima)
    if a == b and b == c:
        print("TRIANGULO EQUILATERO")
    elif a == b or b == c: # Como 'a' é o maior, não precisamos checar a == c
        print("TRIANGULO ISOSCELES")