# -*- coding: utf-8 -*-
"""Checkpoint #1 - Computer Science

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbqS0N1pLKuWbZ4Y1yI3Mr1KQDnsEfDW

#  Exercício 1
"""

# Lista de números inicial
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

pares = []
impares = []

for numero in numeros:
    # Verifica se o número é par
    if numero % 2 == 0:  # == É o operador de comparação de igualdade.
        pares.append(numero)
    # Se não for par, é ímpar
    else:
        impares.append(numero)

print(f"Lista Original: {numeros}")
print(f"Números Pares: {pares}")
print(f"Números Ímpares: {impares}")

"""#Exercício 2"""

# Dicionário Inicial

inventario = {
    "celulares": [],
    "notebooks": []
}

# 1. Adicionando três produtos à categoria "celulares"
inventario["celulares"].append("iPhone 15")
inventario["celulares"].append("Galaxy S24")
inventario["celulares"].append("Pixel 8")

# 2. Adicionando dois produtos à categoria "notebooks"
inventario["notebooks"].append("Macbook Pro")
inventario["notebooks"].append("Dell XPS")

# 4. Exibindo quantos produtos existem em cada categoria
# Usamos a função len() para obter o número de itens em cada lista
print(f"Quantidade de celulares em estoque: {len(inventario['celulares'])}")
print(f"Quantidade de notebooks em estoque: {len(inventario['notebooks'])}")
print() # Adiciona uma linha em branco para separar as seções

# 5. Exibindo o inventário completo
print("--- Inventário Completo ---")

for categoria, produtos in inventario.items():       #.items() - Transforma o dicionário em uma lista de pares
    print(f"{categoria.capitalize()}:")              # Capitalize coloca a primeira letra da categoria em maiúsculo

    for produto in produtos:
        print(f"  - {produto}")

"""#Exercício 3"""

agenda = [
    {"nome": "Alice", "telefone": "9999-1234", "email": "alice@email.com"},
    {"nome": "Bruno", "telefone": "9888-5678", "email": "bruno@email.com"},
    {"nome": "Carlos", "telefone": "9777-4321", "email": "carlos@email.com"},
    {"nome": "Diana", "telefone": "9666-8765", "email": "diana@email.com"}
]

nome_busca = input("Digite o nome do contato que deseja encontrar: ")

# Percorre a lista de contatos
for contato in agenda:
  # Compara os nomes ignorando maiúsculas e minúsculas
  if contato["nome"].lower() == nome_busca.lower():         #.lower() - Isso garante que a busca não diferencie maiúsculas de minúsculas
    contato_encontrado = contato
    break # Interrompe o loop pois o contato foi encontrado

# Verifica se o contato foi encontrado e exibe as informações
if contato_encontrado:
  print("\n--- Contato Encontrado! ---")
  print(f"Nome: {contato_encontrado['nome']}")
  print(f"Telefone: {contato_encontrado['telefone']}")
  print(f"Email: {contato_encontrado['email']}")
else:
  print("Contato não encontrado.")

"""#Exercício 4"""

import random

def jogar_forca():
    """
    Função principal para executar o jogo da forca.
    """

    palavras = ["desenvolvimento", "python", "computador", "programacao"]


    indice_aleatorio = int(random.random() * len(palavras))
    palavra_secreta = palavras[indice_aleatorio]

    letras_corretas = []
    letras_erradas = []
    tentativas = 6

    print("--- Bem-vindo(a) ao Jogo da Forca! ---")
    print(f"A palavra tem {len(palavra_secreta)} letras.")

    # Loop principal do jogo
    while tentativas > 0:

        palavra_a_exibir = ""
        for letra in palavra_secreta:
            if letra in letras_corretas:
                palavra_a_exibir += letra + " "
            else:
                palavra_a_exibir += "_ "

        print("\nPalavra:", palavra_a_exibir)
        print(f"Tentativas restantes: {tentativas}")
        if letras_erradas:
            print(f"Letras erradas: {' '.join(letras_erradas)}")

        # Verifica se o jogador já venceu
        if "_" not in palavra_a_exibir:
            print("\nParabéns! Você adivinhou a palavra!")
            print(f"A palavra era: {palavra_secreta}")
            break

        # Pede uma letra ao jogador
        letra_digitada = input("Digite uma letra: ").lower()

        # Validação simples para garantir que apenas uma letra foi digitada
        if len(letra_digitada) != 1 or not letra_digitada.isalpha():
            print("Por favor, digite apenas uma letra.")
            continue

        # Verifica se a letra já foi tentada antes
        if letra_digitada in letras_corretas or letra_digitada in letras_erradas:
            print("Você já tentou essa letra. Tente outra.")
            continue

        # Verifica se a letra está na palavra secreta
        if letra_digitada in palavra_secreta:
            print("Boa! A letra está na palavra.")
            letras_corretas.append(letra_digitada)
        else:
            print("Que pena! A letra não está na palavra.")
            tentativas -= 1
            letras_erradas.append(letra_digitada)

    # Verifica se o jogador perdeu
    if "_" in palavra_a_exibir:
        print("\nVocê perdeu! Acabaram as tentativas.")
        print(f"A palavra secreta era: {palavra_secreta}")

# Inicia o jogo
if __name__ == "__main__":
    jogar_forca()

"""#Exercício 5"""

frase = "O Python é uma linguagem de programação poderosa e fácil de aprender. Em breve, você dominará o Python e todo este poder como dev."

# 1. Converter para minúsculas para desconsiderar maiúsculas/minúsculas
texto = frase.lower()

# 2. Remover pontuações básicas (vírgula e ponto final), conforme solicitado.
texto_limpo = texto.replace(',', '').replace('.', '')

# 3. Dividir a frase em uma lista de palavras
palavras = texto_limpo.split()

# 4. Contar a frequência de cada palavra usando um dicionário
frequencia = {}
for palavra in palavras:
    # Se a palavra já está no dicionário, incrementa o contador
    if palavra in frequencia:
        frequencia[palavra] += 1
    # Se não, adiciona a palavra ao dicionário com contagem 1
    else:
        frequencia[palavra] = 1

# 5. Exibir os resultados no formato exato da Imagem 2
print("--- Frequência de Palavras ---")
for palavra, contagem in frequencia.items():
    print(f"'{palavra}': apareceu {contagem} vez(es)")